테이블 생성
hakwon-system/hakwon-system pull request #1
Opened 2023-08-21 13:15 UTC by YunSinHo

2023-08-22 23:36 UTC, HanJaehee requested changes

2023-08-22 23:36 UTC, HanJaehee commented on src/main/java/com/ld/user/controller/LoginController.java
> +        if (studentVO.size() != 0) {
사이즈 체크할땐 isEmpty()나 isNotEmpty() 사용하는게 좋을듯

2023-08-22 23:36 UTC, HanJaehee commented on src/main/java/com/ld/user/controller/LoginController.java
> +    @PostMapping("/idCheckTeacher.do")
PostMapping으로 바꾼이유가?

2023-08-22 23:36 UTC, HanJaehee commented on src/main/resources/sql/schema/admin.sql
> +	id int auto_increment primary key,
정렬이 안맞는것같은데 커밋 옵션에 reformat code ㄱㄱ

2023-08-22 23:36 UTC, HanJaehee commented on src/main/resources/sql/schema/modify.sql
> +alter table student modify password varchar(100);
table alter문은 빼고 schema 생성 쿼리에 그대로 포함하는게 나을듯

2023-08-22 23:45 UTC, HanJaehee reviewed
test

2023-08-23 04:39 UTC, YunSinHo commented on src/main/java/com/ld/user/controller/LoginController.java
> +    @PostMapping("/idCheckTeacher.do")
이름과 아이디 보안 유지 떄문

2023-08-23 04:39 UTC, YunSinHo commented on src/main/java/com/ld/user/controller/LoginController.java
> +        if (studentVO.size() != 0) {
ok

2023-08-23 04:40 UTC, YunSinHo commented on src/main/resources/sql/schema/admin.sql
> +	id int auto_increment primary key,
ok

2023-08-23 04:40 UTC, YunSinHo commented on src/main/resources/sql/schema/modify.sql
> +alter table student modify password varchar(100);
ok

2023-08-29 07:03 UTC, merged